line-length = 88
lint.select = ["E", "F"]
lint.ignore = []
lint.fixable = ["ALL"]
lint.unfixable = []

exclude = [
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "__pycache__",
]

[format]
quote-style = "double"
indent-style = "space"